baseURL = "http://example.org/"
languageCode = "en-us"
title = "Loris.space"
theme = "monkey-theme"
paginate = 2

[markup]

[markup.highlight]
style = "dracula"

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class='fas fa-home'></i>"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 4

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"
weight = 5
